/** Evaluation-only temporal proposals and role/scorer ablation. */
import { analyzeMidi } from "../../src/domain/midi/analysis";
import { parseChordLabel } from "../../src/domain/chords";
import { parseMidi } from "../../src/domain/midi/parser";
import { normalizeNotes } from "../../src/domain/midi/normalize";
import { buildVoices, voiceId } from "../../src/domain/midi/voices";
import { annotateVoiceRolesV2 } from "../../src/domain/midi/voiceRoleV2";
import { generateCandidates } from "./candidateRepresentations";
import type { GoldFile } from "./tier1Harness";
type BoundaryMode="fixed-beat"|"onset-cluster"|"change-point"|"lattice"|"product";
const modes:readonly BoundaryMode[]=["fixed-beat","onset-cluster","change-point","lattice","product"];
const eq=(a:number,b:number)=>Math.abs(a-b)<.001;
function sourceEnd(file:GoldFile){const d=parseMidi(file.bytes);return Math.max(...d.notes.map(n=>(n.startTick+n.durationTick)/d.ticksPerBeat));}
function onset(file:GoldFile):number[]{const d=parseMidi(file.bytes),map=new Map<number,number>();for(const n of d.notes){const t=n.startTick/d.ticksPerBeat;map.set(t,(map.get(t)??0)+1);}return [...map].filter(([t,count])=>t>0&&count>=2).map(([t])=>t).sort((a,b)=>a-b);}
function change(file:GoldFile):number[]{const d=parseMidi(file.bytes),end=sourceEnd(file),sets: Set<number>[]=[];for(let t=0;t<end;t+=.5)sets.push(new Set(d.notes.filter(n=>n.startTick/d.ticksPerBeat<t+.5&&(n.startTick+n.durationTick)/d.ticksPerBeat>t).map(n=>n.pitch%12)));const out:number[]=[];for(let i=1;i<sets.length;i++){const a=sets[i-1]!,b=sets[i]!;const union=new Set([...a,...b]);const diff=[...union].filter(p=>a.has(p)!==b.has(p)).length;if(union.size>=2&&diff/union.size>=.6)out.push(i*.5);}return out;}
export function proposeBoundaries(file:GoldFile,mode:BoundaryMode):number[]{const end=sourceEnd(file),fixed=Array.from({length:Math.ceil(end)-1},(_,i)=>i+1).filter(t=>t<end);if(mode==="fixed-beat")return fixed;if(mode==="onset-cluster")return onset(file);if(mode==="change-point")return change(file);if(mode==="product")return analyzeMidi(file.bytes,{enablePresentationGrouping:false}).fullTimeline.slice(1).map(p=>(p.bar-1)*4+p.beat-1);return [...new Set([...fixed,...onset(file),...change(file)])].sort((a,b)=>a-b).slice(0,128);}
interface BoundaryCount { files:number;gold:number;proposed:number;hit:number;halfBeatHit:number;oneBeatHit:number;maxPerFile:number }
export function evaluateBoundaries(files:readonly GoldFile[]):Record<BoundaryMode,BoundaryCount>{const result=Object.fromEntries(modes.map(m=>[m,{files:0,gold:0,proposed:0,hit:0,halfBeatHit:0,oneBeatHit:0,maxPerFile:0}])) as Record<BoundaryMode,BoundaryCount>;for(const file of files){const gold=file.events.slice(1).map(e=>e.startBeat);for(const mode of modes){const out=result[mode],p=proposeBoundaries(file,mode);out.files++;out.gold+=gold.length;out.proposed+=p.length;out.maxPerFile=Math.max(out.maxPerFile,p.length);out.hit+=gold.filter(g=>p.some(x=>eq(x,g))).length;if(file.category==="half-beat-passing-chord"&&p.some(x=>eq(x,2))&&p.some(x=>eq(x,2.5)))out.halfBeatHit++;if(file.category==="one-beat-passing-chord"&&p.some(x=>eq(x,2))&&p.some(x=>eq(x,3)))out.oneBeatHit++;}}return result;}
interface IdentityCount { events:number;top1:number;top3:number;recall:number }
export function evaluateRoleScorer(files:readonly GoldFile[]):Record<string,IdentityCount>{const result:Record<string,IdentityCount>={};for(const role of ["product-hard","soft-role"] as const)for(const scorer of ["overlap","factor-penalty"] as const)result[role+"/"+scorer]={events:0,top1:0,top3:0,recall:0};for(const file of files){const data=parseMidi(file.bytes),notes=normalizeNotes(data),voices=annotateVoiceRolesV2(buildVoices(data),notes),roleMap=new Map(voices.map(v=>[v.id,{role:v.inferredRole,confidence:v.roleConfidence}]));for(const event of file.events){const gold=parseChordLabel(event.chordSymbol);if(!gold)continue;for(const role of ["product-hard","soft-role"] as const){const input=[...new Set(notes.filter(n=>n.startBeat<event.endBeat&&n.sustainedEndBeat>event.startBeat).filter(n=>{const info=roleMap.get(voiceId(n.trackIndex,n.channel??0));if(info?.role==="percussion")return false;if(info?.role!=="melody")return true;return role==="soft-role"&&info.confidence<.8;}).map(n=>n.pitch))].sort((a,b)=>a-b);const candidates=generateCandidates(input,"factorized");for(const scorer of ["overlap","factor-penalty"] as const){const rows=scorer==="overlap"?candidates:[...candidates].sort((a,b)=>(b.score-.03*b.factors.length)-(a.score-.03*a.factors.length));const out=result[role+"/"+scorer]!,match=(c:typeof rows[number])=>c.root===gold.root&&c.quality===gold.quality&&c.bass===(gold.bass??gold.root);out.events++;if(rows.some(match))out.recall++;if(rows.slice(0,3).some(match))out.top3++;if(rows[0]&&match(rows[0]))out.top1++;}}}}return result;}
