/** Aggregate-only adapter for official BACHI predictions; never records private per-file rows. */
import { readFile } from "node:fs/promises";
import { join } from "node:path";
import { parseChordLabel } from "../../src/domain/chords";
import { harmonyFiles,syntheticFiles,type GoldFile } from "./tier1Harness";
interface Prediction{beat:number;root:number;quality:string|undefined;bass:number}
const quality:Record<string,string>={M:"maj",m:"min",M7:"maj7",m7:"min7",D7:"dom7",7:"dom7",dim:"dim",o:"dim",aug:"aug",m7b5:"min7b5",dim7:"dim7",M9:"maj9",m9:"min9",D9:"dom9",m11:"min11",D13:"dom13",sus2:"sus2",sus4:"sus4"};
function predictions(text:string):Prediction[]{const rows:Prediction[]=[];for(const line of text.split(/\r?\n/)){if(!line.trim())continue;const [time,token]=line.trim().split(/\s+/),parts=token?.split("_");if(!time||!parts||parts.length!==3)throw new Error("Unexpected official BACHI output format.");const root=parseChordLabel(parts[0]!),bass=parseChordLabel(parts[2]!);rows.push({beat:Number(time),root:root?.root??-1,quality:quality[parts[1]!]??undefined,bass:bass?.root??-1});}return rows.sort((a,b)=>a.beat-b.beat);}
interface Aggregate{files:number;events:number;boundaryGold:number;boundaryPredicted:number;boundaryHit:number;rootExact:number;qualityExact:number;bassExact:number;fullExact:number;unknownQuality:number;unavailable:number}
async function score(files:readonly GoldFile[],dir:string,prefix:string):Promise<Aggregate>{const out:Aggregate={files:0,events:0,boundaryGold:0,boundaryPredicted:0,boundaryHit:0,rootExact:0,qualityExact:0,bassExact:0,fullExact:0,unknownQuality:0,unavailable:0};for(const [i,file] of files.entries()){const name=`${prefix}-${String(i).padStart(3,"0")}.txt`,rows=predictions(await readFile(join(dir,name),"utf8"));out.files++;const goldStarts=file.events.slice(1).map(e=>e.startBeat),predStarts=rows.slice(1).map(r=>r.beat);out.boundaryGold+=goldStarts.length;out.boundaryPredicted+=predStarts.length;out.boundaryHit+=goldStarts.filter(g=>predStarts.some(p=>Math.abs(p-g)<.001)).length;for(const event of file.events){out.events++;const gold=parseChordLabel(event.chordSymbol);if(!gold)throw new Error("Gold label unparseable in BACHI adapter.");const mid=(event.startBeat+event.endBeat)/2,pred=[...rows].reverse().find(r=>r.beat<=mid);if(!pred){out.unavailable++;continue;}if(!pred.quality)out.unknownQuality++;const root=pred.root===gold.root,q=pred.quality===gold.quality,bass=pred.bass===(gold.bass??gold.root);if(root)out.rootExact++;if(q)out.qualityExact++;if(bass)out.bassExact++;if(root&&q&&bass)out.fullExact++;}}return out;}
function arg(n:string){const i=process.argv.indexOf(n);return i<0?undefined:process.argv[i+1];}
const corpus=arg("--corpus"),synthetic=arg("--synthetic-output"),harmony=arg("--harmony-output");if(!corpus||!synthetic||!harmony)throw new Error("Local corpus and output directories required.");
for(const [group,files,dir,prefix] of [["synthetic",syntheticFiles(),synthetic,"case"],["harmony-dev",await harmonyFiles(corpus,"dev"),harmony,"dev"],["harmony-validation",await harmonyFiles(corpus,"validation"),harmony,"validation"]] as const)process.stdout.write(JSON.stringify({group,...await score(files,dir,prefix)})+"\n");
