/** P7.0-09 evaluation-only modular interaction tournament. */
import { performance } from "node:perf_hooks";
import { analyzeMidi } from "../../src/domain/midi/analysis";
import { parseChordLabel } from "../../src/domain/chords";
import { parseMidi } from "../../src/domain/midi/parser";
import { normalizeNotes } from "../../src/domain/midi/normalize";
import { buildVoices,voiceId } from "../../src/domain/midi/voices";
import { annotateVoiceRolesV2 } from "../../src/domain/midi/voiceRoleV2";
import { proposeBoundaries } from "./boundaryRoleScorer";
import { generateCandidates,type Candidate } from "./candidateRepresentations";
import { evaluateCopyBaseline,type CopyArm } from "./copyBaselines";
import type { GoldFile } from "./tier1Harness";
type Boundary="product"|"fixed-beat"|"lattice";type Role="product-hard"|"soft-role";type Identity="old"|"new";type Decoder="old"|"C1"|"C2";
export interface Config{ id:string;boundary:Boundary;role:Role;identity:Identity;decoder:Decoder }
export const configs:readonly Config[]=[...(["product"] as const).flatMap(boundary=>(["product-hard","soft-role"] as const).flatMap(role=>(["old","new"] as const).flatMap(identity=>(["old","C1","C2"] as const).map(decoder=>({id:[boundary,role,identity,decoder].join("/"),boundary,role,identity,decoder}))))),...(["fixed-beat","lattice"] as const).flatMap(boundary=>(["product-hard","soft-role"] as const).flatMap(role=>(["old","new"] as const).map(identity=>({id:[boundary,role,identity,"C2"].join("/"),boundary,role,identity,decoder:"C2" as const}))))];
if(configs.length+3>24)throw new Error("Tournament exceeds 24 configurations.");
interface Segment{start:number;end:number;notes:number[];candidates:Candidate[];recallCandidates:Candidate[]}
export interface Metric{events:number;exact:number;tp:number;predicted:number;gold:number;top1:number;top3:number;recall:number;boundaryHits:number;boundaryProposed:number;boundaryGold:number;cardDelta:number;passingPreserved:number;passingTotal:number;runtimeMs:number;maxCandidates:number;peakHeapBytes:number}
const blank=():Metric=>({events:0,exact:0,tp:0,predicted:0,gold:0,top1:0,top3:0,recall:0,boundaryHits:0,boundaryProposed:0,boundaryGold:0,cardDelta:0,passingPreserved:0,passingTotal:0,runtimeMs:0,maxCandidates:0,peakHeapBytes:0});
const same=(a:Candidate,b:Candidate)=>a.root===b.root&&a.quality===b.quality&&a.bass===b.bass;
const start=(p:{bar:number;beat:number})=>(p.bar-1)*4+p.beat-1;
function makeSegments(file:GoldFile,c:Config):Segment[]{
 const d=parseMidi(file.bytes),ns=normalizeNotes(d),roles=annotateVoiceRolesV2(buildVoices(d),ns),map=new Map(roles.map(v=>[v.id,{role:v.inferredRole,confidence:v.roleConfidence}]));
 const end=Math.max(...d.notes.map(n=>(n.startTick+n.durationTick)/d.ticksPerBeat)),points=[...new Set([0,...proposeBoundaries(file,c.boundary).filter(n=>n>0&&n<end),end])].sort((a,b)=>a-b),product=analyzeMidi(file.bytes,{enablePresentationGrouping:false}).fullTimeline;
 return points.slice(0,-1).map((s,i)=>{const e=points[i+1]!,notes=[...new Set(ns.filter(n=>n.startBeat<e&&n.sustainedEndBeat>s).filter(n=>{const r=map.get(voiceId(n.trackIndex,n.channel??0));if(r?.role==="percussion")return false;if(r?.role!=="melody")return true;return c.role==="soft-role"&&r.confidence<.8;}).map(n=>n.pitch))].sort((a,b)=>a-b),mid=(s+e)/2;
  let rows:Candidate[];if(c.identity==="old"){const item=product.find(p=>start(p)<=mid&&start(p)+p.durationBeats>mid);rows=item?[item.chord,...item.alternatives.map(a=>a.chord)].map((chord,index)=>({root:chord.root,quality:chord.quality,bass:chord.bass??chord.root,score:1-.04*index,factors:[]})):[];}else rows=generateCandidates(notes,"factorized");
  return {start:s,end:e,notes,candidates:rows.slice(0,12),recallCandidates:rows};});
}
function decode(segments:readonly Segment[],mode:Decoder,file:GoldFile):Array<Candidate|undefined>{if(mode==="old")return segments.map(s=>s.candidates[0]);const d=parseMidi(file.bytes),onsets=new Map<number,number>();for(const n of d.notes){const t=n.startTick/d.ticksPerBeat;onsets.set(t,(onsets.get(t)??0)+1);}const scores:number[][]=[],backs:number[][]=[];for(let i=0;i<segments.length;i++){const row=segments[i]!.candidates;const previous=segments[i-1]?.candidates??[];scores[i]=row.map((candidate,j)=>{if(i===0)return candidate.score;let best=-Infinity,at=0;for(let k=0;k<previous.length;k++){const prior=previous[k]!,changed=!same(prior,candidate),onsetEvidence=(onsets.get(segments[i]!.start)??0)>=2;const penalty=changed?(mode==="C1"?.12:onsetEvidence?.02:.25):0;const total=(scores[i-1]?.[k]??-Infinity)+candidate.score-penalty;if(total>best){best=total;at=k;}}(backs[i]??=[])[j]=at;return best;});}let index=(scores.at(-1)??[]).reduce((best,score,i,arr)=>score>arr[best]! ? i:best,0);const chosen:Array<Candidate|undefined>=Array(segments.length);for(let i=segments.length-1;i>=0;i--){chosen[i]=segments[i]!.candidates[index];index=backs[i]?.[index]??0;}return chosen;}
function evaluateFile(file:GoldFile,c:Config,out:Metric){const t=performance.now(),segments=makeSegments(file,c),decoded=decode(segments,c.decoder,file),starts=segments.slice(1).map(s=>s.start),goldStarts=file.events.slice(1).map(e=>e.startBeat);out.boundaryGold+=goldStarts.length;out.boundaryProposed+=starts.length;out.boundaryHits+=goldStarts.filter(g=>starts.some(s=>Math.abs(s-g)<.001)).length;out.cardDelta+=Math.abs(segments.length-file.events.length);out.maxCandidates=Math.max(out.maxCandidates,...segments.map(s=>s.recallCandidates.length));if(file.category==="half-beat-passing-chord"||file.category==="one-beat-passing-chord"){out.passingTotal++;const [a,b]=file.events.slice(1).map(e=>e.startBeat);if(starts.some(x=>Math.abs(x-a!)<.001)&&starts.some(x=>Math.abs(x-b!)<.001))out.passingPreserved++;}
 for(const event of file.events){out.events++;const mid=(event.startBeat+event.endBeat)/2,index=segments.findIndex(s=>s.start<=mid&&s.end>mid),segment=segments[index],candidate=decoded[index],truth=new Set(event.goldVoicingMidi),predicted=new Set(segment?.notes??[]),tp=[...predicted].filter(n=>truth.has(n)).length;out.gold+=truth.size;out.predicted+=predicted.size;out.tp+=tp;if(truth.size===predicted.size&&tp===truth.size)out.exact++;const chord=parseChordLabel(event.chordSymbol);if(!chord||!segment)continue;const match=(x:Candidate)=>x.root===chord.root&&x.quality===chord.quality&&x.bass===(chord.bass??chord.root);if(segment.recallCandidates.some(match))out.recall++;if(segment.recallCandidates.slice(0,3).some(match))out.top3++;if(candidate&&match(candidate))out.top1++;}out.runtimeMs+=performance.now()-t;out.peakHeapBytes=Math.max(out.peakHeapBytes,process.memoryUsage().heapUsed);}
export function runTournament(files:readonly GoldFile[]){const rows:Record<string,Metric>={};for(const c of configs){const out=blank();for(const file of files)evaluateFile(file,c,out);rows[c.id]=out;}for(const arm of ["Copy-Oracle","Copy-Simple","Copy-ProductBoundary"] as CopyArm[]){const a=evaluateCopyBaseline(files,arm),out=blank();out.events=a.events;out.exact=a.exact;out.tp=a.truePositive;out.predicted=a.predicted;out.gold=a.gold;out.boundaryHits=a.boundaryHits;out.boundaryProposed=a.boundaries;out.boundaryGold=a.goldBoundaries;rows[arm]=out;}return {configurations:Object.keys(rows).length,rows};}
