/** One-shot, aggregate-only sealed synthetic final evaluation. */
import { createHash } from "node:crypto";
import { readFile,writeFile } from "node:fs/promises";
import { encodeTemporalGoldMidi,temporalCategories,validateTemporalGoldCase,type TemporalGoldCase } from "./temporalGold";
import { runTournament } from "./modularTournament";
import type { GoldFile } from "./tier1Harness";
const expectedHash="dbc0a91cf56a5280ff3e6cccebdfa03ea9231cf2ec220330e33edcff9fc15975";
const selected=["Copy-Oracle","Copy-Simple","Copy-ProductBoundary","product/product-hard/old/old","product/product-hard/old/C2","product/product-hard/new/C2","lattice/product-hard/old/C2","lattice/soft-role/new/C2","fixed-beat/soft-role/new/C2"] as const;
function summary(m:ReturnType<typeof runTournament>["rows"][string]){return {events:m.events,exact:m.exact,noteF1:m.predicted+m.gold?2*m.tp/(m.predicted+m.gold):1,missing:m.gold-m.tp,extra:m.predicted-m.tp,structuralTop1:m.top1,candidateRecall:m.recall,boundaryHits:m.boundaryHits,boundaryGold:m.boundaryGold,boundaryProposed:m.boundaryProposed,passingPreserved:m.passingPreserved,passingTotal:m.passingTotal,cardCountDelta:m.cardDelta,wallMs:m.runtimeMs,maxCandidates:m.maxCandidates};}
export function evaluateFinalCohort(files:readonly GoldFile[]){const total=runTournament(files),overall=Object.fromEntries(selected.map(k=>[k,summary(total.rows[k]!)]));const categories=Object.fromEntries(temporalCategories.map(category=>{const subset=files.filter(f=>f.category===category);if(!subset.length)return [category,null];const result=runTournament(subset);return [category,Object.fromEntries(["Copy-Simple","product/product-hard/old/old","lattice/soft-role/new/C2"].map(k=>[k,{events:result.rows[k]!.events,exact:result.rows[k]!.exact,boundaryHits:result.rows[k]!.boundaryHits,boundaryGold:result.rows[k]!.boundaryGold}]))];}));
 const compare=["product/product-hard/old/old","lattice/soft-role/new/C2"] as const;const paired=Object.fromEntries(compare.map(k=>{let wins=0,ties=0,losses=0;const diffs:number[]=[];for(const file of files){const result=runTournament([file]).rows,base=result["Copy-Simple"]!,candidate=result[k]!;const diff=candidate.exact/candidate.events-base.exact/base.events;diffs.push(diff);if(diff>0)wins++;else if(diff<0)losses++;else ties++;}const mean=diffs.reduce((a,b)=>a+b,0)/diffs.length,variance=diffs.reduce((a,b)=>a+(b-mean)**2,0)/(diffs.length-1),se=Math.sqrt(variance/diffs.length);return [k,{pieces:diffs.length,wins,ties,losses,meanExactRateDeltaVsCopySimple:mean,normalApprox95CI:[mean-1.96*se,mean+1.96*se]}];}));
 return {schemaVersion:1,cohort:"sealed-synthetic-v1",files:files.length,categories:temporalCategories.length,configurationsEvaluated:total.configurations,overall,categoryAggregates:categories,paired};}
export async function loadSealedFiles(input:string,marker:string):Promise<GoldFile[]>{const bytes=await readFile(input),hash=createHash("sha256").update(bytes).digest("hex");if(hash!==expectedHash)throw new Error("Sealed holdout hash mismatch; do not regenerate.");await writeFile(marker,JSON.stringify({holdout:"p7-sealed-synthetic-v1",sha256:hash,consumedAt:new Date().toISOString()}),{flag:"wx"});const payload=JSON.parse(bytes.toString("utf8")) as {version:string;cases:TemporalGoldCase[]};if(payload.version!=="p7-sealed-synthetic-v1"||payload.cases.length!==26)throw new Error("Sealed holdout contract mismatch.");const files:GoldFile[]=payload.cases.map(entry=>{const issues=validateTemporalGoldCase(entry);if(issues.length)throw new Error("Invalid sealed Gold case.");return {bytes:encodeTemporalGoldMidi(entry),category:entry.category,events:entry.voicingSpans.map(span=>({startBeat:span.startBeat,endBeat:span.endBeat,chordSymbol:entry.harmonicSpans.find(h=>h.startBeat<=span.startBeat&&h.endBeat>span.startBeat)?.identity??"",goldVoicingMidi:[...span.targetMidi]}))};});return files;}
